#################################### common config : ####################################
# 应用服务web访问端口
server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  application:
    name: community-cae
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    static-path-pattern: /static/**
  # redis配置
  redis:
    host: 192.168.0.105
    port: 6379
    password:
    timeout: 36000
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 5
        max-wait: 10000

  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/yl_cfra?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 600
    timeBetweenEvictionRunsMillis: 600
    minEvictablIdleTimeMills: 3000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    autoCommit: true
  #设置开启热部署
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.community.cae.entity
  #枚举类扫描，支持统配符 * 或者 ; 分割
  #  typeEnumsPackage: com.soonphe.portal.entity.constant
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置——未删除0 已删除1
      logic-delete-value: 1
      logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 上传文件统一后缀名称配置
custom:
  image_upload_ext: jpg,png,gif,ico,doc,docx,jpeg,apk,xls,xlsx,mp4,flv,swf,avi,mp3,pdf,txt
  audio_upload_ext: mp4,flv,swf,mkv,avi,rm,rmvb,mpeg,mpg,ogg,ogv,mov,wmv,webm,mp3,wav,mid
  image_src: d:/myfile/upload/
  ueditor_image_path: d:/myfile/upload/ueditor/
#  ueditor_image_path: /home/upload/ueditor/
#  image_src: /home/upload/
  certificate_download_url: http://hengtong.yl-mall.cn/



